version: '3.5'
services:
    frontend:
        image: nginx:alpine
        volumes:
            - $PWD/frontend.html:/usr/share/nginx/html/index.html
        networks:
            my-network-name:
                aliases:
                    - frontend
    backend:
        depends_on:
            - mysql-database
        image: nginx:alpine
        volumes:
            - $PWD/backend.html:/usr/share/nginx/html/index.html
        networks:
            my-network-name:
                aliases:
                    - backend
    nginx-proxy:
        depends_on:
            - frontend
            - backend
        image: nginx:alpine
        volumes:
            - $PWD/default.conf:/etc/nginx/conf.d/default.conf
        networks:
            my-network-name:
                aliases:
                    - proxy
        ports:
            - 8080:80
    mysql-database:
        image: mysql
        command: --default-authentication-plugin=mysql_native_password
        restart: always
        environment:
            MYSQL_DATABASE: 'root'
            MYSQL_ROOT_PASSWORD: 'secret'
        ports:
            - '3306:3306'
        networks:
            my-network-name:
                aliases:
                    - mysql
networks:
    my-network-name:
